name: Travel Tracker

on:
  schedule:
    # Morning samples
    - cron: "45 4 * * 1-5"
    - cron: "55 4 * * 1-5"
    - cron: "05 5 * * 1-5"
    # Evening samples
    - cron: "30 11 * * 1-5"
    - cron: "00 12 * * 1-5"
    - cron: "30 12 * * 1-5"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        env:
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: python track_travel.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "Update travel stats" || echo "No changes"
          git push
